[providers]
  php = "8.3"
  nodejs = "18"

[variables]
  PORT = "8080"

[phases.setup]
  nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_pgsql", "php83Extensions.pgsql", "nodejs_18", "npm"]

[phases.install]
  cmds = [
    "composer install --no-dev --optimize-autoloader"
  ]

[phases.build]
  cmds = [
    "npm ci",
    "npm run build",
    "php artisan config:clear"
  ]

[phases.start]
  cmd = "php server.php"